-- 코드를 입력하세요
SELECT 
    ID, NAME, A.HOST_ID
FROM PLACES AS A
LEFT JOIN(
    SELECT HOST_ID, COUNT(ID) AS CNT
    FROM PLACES
    GROUP BY HOST_ID) AS B 
ON A.HOST_ID = B.HOST_ID
WHERE CNT > 1
ORDER BY ID ASC