-- 코드를 작성해주세요
SELECT 
    EMP_NO,
    EMP_NAME,
    CASE
        WHEN SCORE >= 96 THEN "S"
        WHEN SCORE >= 90 THEN "A"
        WHEN SCORE >= 80 THEN "B"
        ELSE "C"
    END AS GRADE,
    CASE
        WHEN SCORE >= 96 THEN (SAL * 0.2)
        WHEN SCORE >= 90 THEN (SAL * 0.15)
        WHEN SCORE >= 80 THEN (SAL * 0.1)
        ELSE 0
    END AS BONUS
FROM (SELECT 
    A.EMP_NO,
    EMP_NAME,
    AVG(SCORE) AS SCORE,
    SAL
FROM HR_GRADE AS A
LEFT JOIN HR_EMPLOYEES AS B
ON A.EMP_NO = B.EMP_NO
LEFT JOIN HR_DEPARTMENT AS C
ON B.DEPT_ID = C.DEPT_ID
GROUP BY EMP_NO) D
ORDER BY EMP_NO ASC