-- 아이스크림 가게의 주문 정보 테이블 FIRST_HALF
-- 아이스크림 성분에 대한 정보 ICECREAM_INFO

SELECT
    A.FLAVOR AS FLAVOR
FROM
    FIRST_HALF AS A
INNER JOIN 
    ICECREAM_INFO AS B
ON 
    A.FLAVOR = B.FLAVOR
WHERE
    A.TOTAL_ORDER > 3000 AND B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY
    A.TOTAL_ORDER DESC
    