-- 코드를 작성해주세요

SELECT
    SUM(SCORE) AS SCORE,
    A.EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM HR_EMPLOYEES AS A
LEFT JOIN HR_GRADE AS B
ON A.EMP_NO = B.EMP_NO
LEFT JOIN HR_DEPARTMENT AS C
ON A.DEPT_ID = C.DEPT_ID
GROUP BY EMP_NAME, A.EMP_NO, POSITION, EMAIL
ORDER BY SCORE DESC
LIMIT 1
